USE aethoria_db;

DROP TABLE IF EXISTS DESARROLLADOR;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS TIPO_ITEM;
DROP TABLE IF EXISTS HABILIDAD;
DROP TABLE IF EXISTS CLASE;
DROP TABLE IF EXISTS ROL;

CREATE TABLE ROL (
    id_rol INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    descripcion TEXT
);

CREATE TABLE CLASE (
    id_clase INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    descripcion TEXT,
    id_rol INT NOT NULL,
    FOREIGN KEY (id_rol) REFERENCES ROL(id_rol)
);

CREATE TABLE HABILIDAD (
    id_habilidad INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    descripcion TEXT,
    daño INT,
    id_clase INT NOT NULL,
    FOREIGN KEY (id_clase) REFERENCES CLASE(id_clase)
);

CREATE TABLE TIPO_ITEM (
    id_tipo INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE ITEM (
    id_item INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    rareza VARCHAR(50),
    id_tipo INT NOT NULL,
    FOREIGN KEY (id_tipo) REFERENCES TIPO_ITEM(id_tipo)
);

CREATE TABLE USUARIO (
    id_usuario INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    fecha_registro DATE DEFAULT (CURRENT_DATE)
);

CREATE TABLE DESARROLLADOR (
    id_dev INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);